name: Env-Action
on:
 workflow_dispatch:
 
jobs:
 deploy:
   runs-on: ubuntu-latest
   strategy: 
     matrix: 
       environment: [pro, dev]
   env:
    ENV_VAR : ${{ secrets[matrix.environment] }}
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Show environment variable
       run: echo "La variable del entorno ${{ matrix.environment }} es ${{ env.ENV_VAR }}"
       
